package com.example.assignment3_relationshipcounter.service.firestore;

import android.util.Log;

import com.example.assignment3_relationshipcounter.service.models.User;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QueryDocumentSnapshot;
import com.google.firebase.messaging.FirebaseMessaging;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

public class DataUtils {

    private final FirebaseFirestore db;

    public DataUtils() {
        this.db = FirebaseFirestore.getInstance();
    }

    //NORMAL CRUD REQUEST

    /**
     *Update whole document or update one field in document using ID
     */
    public <T> void updateById(String collection, String id, T data, NormalCallback<T> callback) {
        db.collection(collection).document(id).set(data)
                .addOnSuccessListener(aVoid -> {
                    callback.onSuccess();
                })
                .addOnFailureListener(e -> {
                    callback.onFailure(new Exception("Cannot update data"));
                });
    }

    public <T> void updateOneFieldById(String collection, String id, String field, T value, NormalCallback<Void> callback) {
        db.collection(collection).document(id).update(field, value)
                .addOnSuccessListener(aVoid -> {
                    callback.onSuccess();
                })
                .addOnFailureListener(e -> {
                    callback.onFailure(new Exception("Cannot update data"));
                });
    }

    /**
     * Add new document, the object's id will be generated by Firestore
     */
    public <T extends HasId> void add(String collection, T data, NormalCallback<T> callback){
        DocumentReference docRef;

        if(data instanceof User){
            docRef = db.collection(collection).document(new Authentication().getFUser().getUid());
        }
        else {
           docRef = db.collection(collection).document();
        }

        String generatedId = docRef.getId(); // Get the generated ID
        // Set the ID in the object
        data.setId(generatedId);

        docRef.set(data)
            .addOnSuccessListener(aVoid -> {
                callback.onSuccess();
            })
            .addOnFailureListener(e -> {
                callback.onFailure(new Exception("Cannot add new data"));
            });
    }

    /**
     * Delete the document by ID
     */
    public <T> void deleteById(String collection, String id, NormalCallback<T> callback) {
        db.collection(collection).document(id).delete()
                .addOnSuccessListener(aVoid -> {
                    callback.onSuccess();
                })
                .addOnFailureListener(e -> {
                    callback.onFailure(new Exception("Cannot delete the data"));
                });
    }


    /**
     * Get one document by ID or get all document in collection (the callback on getAll return a list)
     */
    public <T> void getById(String collection, String id, Class<T> object, FetchCallback<T> callback) {
        db.collection(collection).document(id).get()
                .addOnSuccessListener(documentSnapshot -> {
                    if (documentSnapshot.exists()) {
                        T retrievedData = documentSnapshot.toObject(object);
                        if (retrievedData != null) {
                            callback.onSuccess(retrievedData);
                        } else {
                            callback.onFailure(new Exception("Data is null"));
                        }
                    }
                });
    }


    public <T> void getAll(String collection, Class<T> objectClass, FetchCallback<List<T>> callback) {
        db.collection(collection).get()
                .addOnSuccessListener(queryDocumentSnapshots -> {
                    if (!queryDocumentSnapshots.isEmpty()) {
                        List<T> dataList = new ArrayList<>();
                        for (QueryDocumentSnapshot document : queryDocumentSnapshots) {
                            T retrievedData = document.toObject(objectClass);
                            if (retrievedData != null) {
                                dataList.add(retrievedData);
                            }
                        }
                        callback.onSuccess(dataList); // Pass the list to onSuccess
                    } else {
                        callback.onSuccess(Collections.emptyList()); // Pass an empty list if no documents are found
                    }
                })
                .addOnFailureListener(callback::onFailure); // Pass the exception to onFailure
    }

    /**
     * Function use for update the daily counter
     * @see DailyFriendUpdateWorker
     * It called this function daily to updating the counter
     */

    public void updateCounterDaily( NormalCallback<Void> callback){
        db.collection("relationships")
            .whereEqualTo("status", "FRIEND") // Match only FRIEND status
            .get()
            .addOnSuccessListener(querySnapshot -> {
                if(querySnapshot.isEmpty()){
                    return;
                }
                for (QueryDocumentSnapshot document : querySnapshot) {
                    // Get the current counter value
                    int currentCounter = Objects.requireNonNull(document.getLong("counter")).intValue();

                    // Increment the counter
                    db.collection("relationships")
                            .document(document.getId())
                            .update("counter", currentCounter + 1)
                            .addOnSuccessListener(aVoid -> {
                                System.out.println("Counter updated for document: " + document.getId());
                            })
                            .addOnFailureListener(e -> {
                                System.err.println("Failed to update counter for document: " + document.getId());
                            });
                }
            })
            .addOnFailureListener(e -> {
                System.err.println("Failed to fetch documents: " + e.getMessage());
            });
    }

    public interface NormalCallback<T> {
        void onSuccess();
        void onFailure(Exception e);
    }

    public interface FetchCallback<T>{
        void onSuccess(T data);
        void onFailure(Exception e);
    }


    public interface HasId {
        void setId(String id);
    }


    /**
     * FCM token getter
     */
    public void getFCMToken(String userId){
        FirebaseMessaging.getInstance().getToken().addOnCompleteListener(task -> {
           if(task.isSuccessful()){
               String token = task.getResult();
               updateOneFieldById("users",userId, "fcmToken", token, new NormalCallback<Void>(){
                   @Override
                   public void onSuccess() {
                       System.out.println("FCM token updated successfully.");
                   }
                   @Override
                   public void onFailure(Exception e) {
                       System.err.println("Failed to update FCM token: " + e.getMessage());
                   }
               });
           }
        });
    }

}
